version: "3.8"
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - 3306:3306
        volumes:
            - .:/var/www/application
            - .docker/mysql/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/mysql/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    php:
        build: .docker/php-7.4
        working_dir: /var/www/application
        volumes:
            - .:/var/www/application
            - .docker/php-7.4/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - .docker/php-7.4/usr/local/etc/php/conf.d/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
        ports:
            - 9000:9000
    apache:
        image: httpd:2.4
        volumes:
            - .:/var/www/application
            - .docker/httpd/usr/local/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - .docker/httpd/etc/apache2/sites-enabled:/etc/apache2/sites-enabled
        ports:
            - 80:80
    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
    blackfire:
        image: blackfire/blackfire
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: e77e62c6-07d5-430d-b035-758dbef2659a
            BLACKFIRE_SERVER_TOKEN: 1e6561878612f2c2cba4e88f52e3e007f2e22cc253a9c7170183707a1b02a23d
            BLACKFIRE_CLIENT_ID: 7de0f057-dbe0-48fd-bf89-8b5f8858e294
            BLACKFIRE_CLIENT_TOKEN: 47b2cb5f0659c3e73266bfa38d0d74ca03f8b4ecb9563f237992a4c38804280f
            # BLACKFIRE_SERVER_ID: ~
            # BLACKFIRE_SERVER_TOKEN: ~
            # BLACKFIRE_CLIENT_ID: ~
            # BLACKFIRE_CLIENT_TOKEN: ~
    adminer:
        image: adminer
        ports:
        - 8080:8080
